import os
from pathlib import Path
from dotenv import load_dotenv
from core.env_utils import env_bool, load_schedule

load_dotenv()

SCHEDULE = load_schedule()

BOT_HEADLESS = env_bool("BOT_HEADLESS", True)
# BOT_ENV = os.getenv("BOT_ENV", "prod")

LOGIN_URL = os.getenv("LOGIN_URL")
POST_LOGIN_URL = os.getenv("POST_LOGIN_URL")
INSIDE_SYSTEM_URL_PATTERN = os.getenv("INSIDE_SYSTEM_URL_PATTERN")
GYM_CLASS_VERIFICATION_URL = os.getenv("GYM_CLASS_VERIFICATION_URL")
POTENTIAL_MODAL_ENTIENDO_SELECTOR = os.getenv("POTENTIAL_MODAL_ENTIENDO_SELECTOR")
POTENTIAL_INTERMEDIATE_LOGIN_SELECTOR = os.getenv(
    "POTENTIAL_INTERMEDIATE_LOGIN_SELECTOR"
)
INSIDE_SYSTEM_PATTERN_URL = os.getenv("INSIDE_SYSTEM_PATTERN_URL")


COMPENSAR_DOC_TYPE = os.getenv("COMPENSAR_DOC_TYPE")
COMPENSAR_DOC_NUM = os.getenv("COMPENSAR_DOC_NUM")
COMPENSAR_PASSWORD = os.getenv("COMPENSAR_PASSWORD")

BOT_FORCE_RUN = env_bool("BOT_FORCE_RUN", False)
BOT_FORCE_RUN_CLASS = os.getenv("BOT_FORCE_RUN_CLASS")
BOT_FORCE_RUN_HOUR = os.getenv("BOT_FORCE_RUN_HOUR")
BOT_FORCE_RUN_DAY = os.getenv("BOT_FORCE_RUN_DAY")

ADDITIONAL_MINUTE_FOR_EXECUTION = env_bool("ADDITIONAL_MINUTE_FOR_EXECUTION", False)

TOKEN = os.getenv("TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

WAKEALARM_PATH = str(os.getenv("WAKEALARM_PATH"))
WAKE_MINUTES_BEFORE = int(os.getenv("WAKE_MINUTES_BEFORE", 3))
SLEEP_MINUTES_AFTER = int(os.getenv("SLEEP_MINUTES_AFTER", 3))
