from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    import re

    from playwright.sync_api import ViewportSize


class IElementHandle(Protocol):
    def inner_text(self) -> str: ...
    def click(self, **kwargs: Any) -> None: ...
    def bounding_box(self) -> dict[str, float] | None: ...
    def is_visible(self) -> bool: ...
    def hover(self, **kwargs: Any) -> None: ...


class ILocator(Protocol):
    def count(self) -> int: ...
    def nth(self, index: int) -> ILocator: ...
    def is_visible(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def inner_text(self) -> str: ...
    def click(self, **kwargs: Any) -> None: ...


class IMouse(Protocol):
    def wheel(self, delta_x: float, delta_y: float) -> None: ...
    def move(self, x: float, y: float, **kwargs: Any) -> None: ...
    def click(self, x: float, y: float, **kwargs: Any) -> None: ...


class IKeyboard(Protocol):
    def type(self, text: str, **kwargs: Any) -> None: ...
    def press(self, key: str, **kwargs: Any) -> None: ...


class IPage(Protocol):
    @property
    def url(self) -> str: ...
    @property
    def viewport_size(self) -> ViewportSize | None: ...

    @property
    def mouse(self) -> IMouse: ...
    @property
    def keyboard(self) -> IKeyboard: ...

    def goto(self, url: str, **kwargs: Any) -> Any: ...
    def wait_for_selector(self, selector: str, **kwargs: Any) -> IElementHandle | None: ...
    def click(self, selector: str, **kwargs: Any) -> None: ...
    def select_option(self, selector: str, **kwargs: Any) -> list[str]: ...
    def query_selector_all(self, selector: str) -> list[IElementHandle]: ...
    def query_selector(self, selector: str) -> IElementHandle | None: ...
    def locator(self, selector: str, **kwargs: Any) -> ILocator: ...
    def evaluate(self, expression: str, arg: Any = None, **kwargs: Any) -> Any: ...
    def wait_for_load_state(self, state: str, **kwargs: Any) -> None: ...
    def wait_for_url(self, url: str | re.Pattern[str], **kwargs: Any) -> None: ...
    def wait_for_timeout(self, timeout: int) -> None: ...
    def content(self) -> str: ...
    def reload(self, **kwargs: Any) -> None: ...
    def screenshot(self, **kwargs: Any) -> bytes: ...
    def set_default_timeout(self, timeout: int) -> None: ...
