timezone: America/Bogota

dias:
  lunes:
    - nombre: Tono Mixto
      hora: "05:00 - 06:00"
    - nombre: Pilates
      hora: "06:00 - 07:00"
    - nombre: Estiramientos
      hora: "07:00 - 08:00"

  miércoles:
    - nombre: Pilates
      hora: "05:00 - 06:00"
    - nombre: Yoga
      hora: "06:00 - 07:00"
    - nombre: Entrenamiento Funcional
      hora: "06:00 - 07:00"
    - nombre: Pilates
      hora: "07:00 - 08:00"
  
  jueves:
    - nombre: Estiramientos
      hora: "07:00 - 08:00"

  sábado:
    - nombre: Pilates
      hora: "06:00 - 07:00"
    - nombre: Bases Inestables
      hora: "07:00 - 08:00"

