environment:
  login_url: https://seguridad.compensar.com/sign-in?serviceProviderName=HER-SP&protocol=SAML
  inside_system_url: https://sistemaplanbienestar.deportescompensar.com/entrenamiento/reserva/practica/libre
  inside_system_url_pattern: "**compensar.com/**"

os:
  home_user: "~"
  firefox_path: /usr/bin/firefox
  chromium_path: /usr/bin/chromium

selectors:
  potential_temporary_platform_notification: "button[type='submit']:has-text('Entendido')"
  potential_modal_entiendo_selector: "button[type='submit']:has-text('Entiendo')"
  potential_intermediate_login_selector: "#presso-login"

power_autonomous:
  wake_minutes_before: 5
  sleep_minutes_after: 10
  wakealarm_path: /sys/class/rtc/rtc0/wakealarm

execution:
  bot_force_run: false
  seconds_for_temporary_platform_notifications: 11
  execution_adjustment: -3
  bot_headless: false
  run_device: Galaxy S24 # desktop, GALAXY_S24, iPhone 15 Pro Max
